name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repo to server
      uses: appleboy/scp-action@v0.1.4
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/mahyarshabani-website/application"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          sudo lsof -t -i:3000 | xargs kill -9
          ls /home/mahyarshabani-website/
          cd /home/mahyarshabani-website/application
          # docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          # docker pull ghcr.io/my_github_username/my_repository_name/my_image_name:latest
          sudo docker stop mahyarshabani-website || true
          sudo docker system prune -f
          sudo docker build -t mahyarshabani-website-image .
          sudo docker run -d --rm -p 3000:3000 --name mahyarshabani-website mahyarshabani-website-image